eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:school

application:
  config:
    students-url: http://localhost:8090/api/v1/students

server:
  port: 8070