eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: STUDENTS
          uri: lb://STUDENTS
          predicates:
            - Path=/api/v1/students/**
        - id: SCHOOLS
          uri: lb://SCHOOLS
          predicates:
            - Path=/api/v1/schools/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
